### PR TITLE
Set cookies on redirects

### LINKED ISSUE #24: where is the cookie jar set to requests?
I'm having problems with the cookie jar not working (cookies are not persisted through redirects in a GET call).
I'm reading through the code, and I couldn't find where the jar variable is set to the request instance. I'm trying to debug what I'm doing wrong. 

I'm doing this:
```js
  this.cookies = popsicle.jar()
  this.request = popsicle.defaults({
    options: { jar: this.cookies }
  })
```

and then doing the request like so:
```js
  this.request.get({
    url: this.info.url,
  })
  .then((response) => {
    var fs = require('fs');
    fs.writeFileSync('output.html', response.body)
  })

```
The URL I'm GETting redirects 2 times, setting cookies. 
But from the result and debugging the requests, the cookies are not being set and sent in the 2nd and 3rd requests. 
I've been following the `jar` option down to https://github.com/blakeembrey/popsicle/blob/v1.2.1/lib/base.ts#L46 and it doesn't seem to be set. Could it be that it's not set, or that I'm doing something wrong? Could you point to the line where the jar option is set?

Thanks for your time!

### PR DESCRIPTION
**Pull request by blakeembrey**
* Move cookie jar logic into request and out of the default plugins
* Remove `through2` and replaced with a PassThrough stream instance
* Replace `faucet` with `tap-dot` for better tap reports

Closes #24

### CODE REVIEW

**Comment by maraoz** [comment]
Cool, thanks for fixing the regression. Can you release a new version so I can see if this PR fixes my issue? (my branch works for me, but I'd rather use the official version)

**Comment by blakeembrey** [comment]
Yes, of course :+1: I'm just merging another patch and then I'll push out a minor release for you.

**Comment by maraoz** [comment]
Thanks!

**Comment by blakeembrey** [comment]
Done. Released with `v1.3.0` :smile: Please let me know if there's any other issues.

**Comment by maraoz** [comment]
Works like a charm! Thank you again!

**Pull request merged**
